# Generated by Django 2.2.1 on 2019-05-19 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='media')),
                ('subject', models.CharField(choices=[('chinese', '语文'), ('math', '数学'), ('english', '英语')], max_length=20, verbose_name='科目')),
                ('grade', models.CharField(choices=[('1', '一年级上'), ('2', '一年级下'), ('3', '二年级上'), ('4', '二年级下'), ('5', '三年级上'), ('6', '三年级下'), ('7', '四年级上'), ('8', '四年级下'), ('9', '五年级上'), ('10', '五年级下'), ('11', '六年级上'), ('12', '六年级下')], max_length=20)),
                ('price', models.FloatField(default=0)),
                ('description', models.CharField(default='', max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=16)),
                ('phone', models.CharField(max_length=11)),
                ('is_student', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='UserAndCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_watch', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.User')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('chinese', '语文'), ('math', '数学'), ('english', '英语')], max_length=20, verbose_name='科目')),
                ('sex', models.IntegerField(default=0)),
                ('education', models.CharField(max_length=20)),
                ('teaching_age', models.IntegerField(default=0)),
                ('teach_code', models.CharField(max_length=20)),
                ('picture', models.ImageField(upload_to='media')),
                ('description', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='study.User')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_pay', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.User')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.User')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.Teacher'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.User')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('video', models.FileField(default='', upload_to='media')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.Course')),
            ],
        ),
    ]
