# Generated by Django 2.2.1 on 2019-06-08 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_auto_20190529_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.Chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.User')),
            ],
        ),
    ]
