# Generated by Django 2.2.1 on 2019-06-09 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_userandproblem_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userandproblem',
            name='datetime',
        ),
    ]
